# Generated by Django 4.1.7 on 2023-03-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_remove_item_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='list',
            field=models.TextField(default=''),
        ),
    ]
